fragment CityAliasFragment on CityAliases {
    id
    name
    city {
        id
        name
        state {
            id
            name
            country {
                id
                name
            }
        }
    }
}
