#import "../fragments/category.fragment.gql"

query CategoriesAll ($pagination: Pagination, $sort: Sortable) {
    categories (pagination: $pagination, sort: $sort) {
        data {
            ...CategoryFragment
        }
        total
        hasPages
        lastPage
    }
}

query CategoryByID ($id: [ID]!) {
    categories (filter: {id: $id}) {
        data {
            ...CategoryFragment
        }
    }
}
