#import "../fragments/role.fragment.gql"

query GetRoles ($pagination: Pagination, $sort: Sortable) {
    roles (pagination: $pagination, sort: $sort) {
        data {
            ...RoleFragment
        }
        total
        hasPages
        lastPage
    }
}
