#import "../fragments/user.fragment.gql"

query GetUsers($pagination: Pagination, $sort: Sortable, $filter: UserFilter) {
  users(pagination: $pagination, sort: $sort, filter: $filter) {
    data {
      ...UserFragment
      roles {
        id
        name
        display_name
      }
      city {
        id
        name
        state {
          id
          name
          country {
            id
            name
          }
        }
      }
    }
    total
    hasPages
    lastPage
  }
}
