#import "../fragments/listingType.fragment.gql"

query GetListingTypes($pagination: Pagination, $sort: Sortable, $filter: ListingTypeFilter) {
  listing_types(pagination: $pagination, sort: $sort, filter: $filter) {
    data {
      ...ListingTypeFragment
    }
    total
    hasPages
    lastPage
  }
}
