#import "../fragments/listingType.fragment.gql"

query ListingTypesAll ($pagination: Pagination, $sort: Sortable) {
    listing_types (pagination: $pagination, sort: $sort) {
        data {
            ...ListingTypeFragment
        }
        total
        hasPages
        lastPage
    }
}
