#import "../fragments/cityAlias.fragment.gql"

query CityAliasesAll ($pagination: Pagination, $sort: Sortable, $filter: CityAliasFilter) {
    city_aliases (pagination: $pagination, sort: $sort, filter: $filter) {
        data {
            ...CityAliasFragment
        }
        total
        hasPages
        lastPage
    }
}
