#import "../fragments/country.fragment.gql"

query GetCountries ($pagination: Pagination, $sort: Sortable) {
  countries (pagination: $pagination, sort: $sort) {
    data {
      ...CountryFragment
    }
    total
    hasPages
    lastPage
  }
}
