#import "../fragments/cityAlias.fragment.gql"

query GetCityAliases($pagination: Pagination, $sort: Sortable, $filter: CityAliasFilter) {
  city_aliases(pagination: $pagination, sort: $sort, filter: $filter) {
    data {
      ...CityAliasFragment
    }
    total
    hasPages
    lastPage
  }
}
