#import "../fragments/city.fragment.gql"

query GetCities ($pagination: Pagination, $sort: Sortable, $filter: CityFilter) {
  cities (pagination: $pagination, sort: $sort, filter: $filter) {
    data {
      ...CityFragment
      state {
        id
        name
        country {
          id
          name
        }
      }
    }
    total
    hasPages
    lastPage
  }
}

