#import "../fragments/state.fragment.gql"

query GetStates($pagination: Pagination, $sort: Sortable, $filter: StateFilter) {
  states(pagination: $pagination, sort: $sort, filter: $filter) {
    data {
      ...StateFragment
    }
    total
    hasPages
    lastPage
  }
}
